
export const cards = [
  {
    title: "General Knowledge",
    src: "/anime-boy.jpg",
    category: 9,
    filterValue: "All",
  },
  {
    title: "Entertainment: Books",
    src: "/anime-boy-1.jpg",
    category: 10,
    filterValue: "entertainment",
  },
  {
    title: "Entertainment: Film",
    src: "/anime-girl-3.jpg",
    category: 11,
    filterValue: "entertainment",
  },
  {
    title: "Entertainment: Music",
    src: "/anime-girl-4.jpg",
    category: 12,
    filterValue: "entertainment",
  },
  {
    title: "Entertainment: Musicals & Theatres",
    src: "/anime-girl-6.jpg",
    category: 13,
    filterValue: "entertainment",
  },
  {
    title: "Entertainment: Television",
    src: "/anime-girl-5.jpg",
    category: 14,
    filterValue: "entertainment",
  },
  {
    title: "Entertainment: Video Games",
    src: "/anime-girl-4.jpg",
    category: 15,
    filterValue: "entertainment",
  },
  {
    title: "Entertainment: Board Games",
    src: "/anime-girl-7.jpg",
    category: 16,
    filterValue: "entertainment",
  },
  {
    title: "Science: Nature",
    src: "/anime-boy-2.jpg",
    category: 17,
  },
  {
    title: "Science: Computers",
    src: "/anime-girl-3.jpg",
    category: 18,
    filterValue: "technology",
  },
  {
    title: "Science: Mathematics",
    src: "/dragon.jpg",
    category: 19,
    filterValue: "science",
  },
  {
    title: "Science: Gadgets",
    src: "/whale.jpg",
    category: 30,
    filterValue: "science",
  },
  {
    title: "Mythology",
    src: "/anime-girl-2.jpg",
    category: 20,
    filterValue: "art",
  },
  {
    title: "Sports",
    src: "/anime-girl-1.jpg",
    category: 21,
    filterValue: "sports",
  },
  {
    title: "Geography",
    src: "/ninja.jpg",
    category: 22,
    filterValue: "art",
  },
  {
    title: "History",
    src: "/sad-boy.jpg",
    category: 23,
    filterValue: "art",
  },
  {
    title: "Politics",
    src: "/death.jpg",
    category: 24,
    filterValue: "art",
  },
  {
    title: "Art",
    src: "/grim.jpg",
    category: 25,
    filterValue: "art",
  },
  {
    title: "Celebrities",
    src: "/anime-girl-8.jpg",
    category: 26,
    filterValue: "time pass",
  },
  {
    title: "Animals",
    src: "/animal.jpg",
    category: 27,
    filterValue: "time pass",
  },
  {
    title: "Vehicles",
    src: "/vehicles.jpg",
    category: 28,
    filterValue: "time pass",
  },
  {
    title: "Entertainment: Comics",
    src: "/comic.jpg",
    category: 29,
    filterValue: "entertainment",
  },
  {
    title: "Entertainment: Japanese Anime & Manga",
    src: "/anime.jpg",
    category: 31,
    filterValue: "anime",
  },
  {
    title: "Entertainment: Cartoon & Animations",
    src: "/cartoon.jpg",
    category: 32,
    filterValue: "anime",
  },
];
